<?php
putenv('DISPLAY_ERRORS_DETAILS=' . true);

putenv('UPTECHNOLOGY1_PG_HOST=localhost');

putenv('UPTECHNOLOGY1_PG_DBNAME=');

putenv('UPTECHNOLOGY1_PG_USER=root');

putenv('UPTECHNOLOGY1_PG_PASSWORD=');

putenv('UPTECHNOLOGY1_PG_PORT=3306');

putenv('JWT_SECRET_KEY=mareyJ0eXAcusiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFvinitZSI6eyJpZCI6MTgsInVzZXJuYW1lIjoial9zb3V6YSIsInBhc3N3b3JkIjoiajFvMnMzYTQiLCJleHBpcmVkX2F0IjoiMDctMDctMjMgMTk6MTA6NDcifX0.xdQvbh_DheXdh-1ZuxGHAjtFk20V_0IbtPej1974IRUcius');

?>